### ISSUE TITLE
Running karma start does nothing

### ISSUE THREAD

**Issue by BobbieBarker** [djindjic/generator-jspm-lib#1]
Don't know what else to say.

**Comment by djindjic** [comment]
hmmm, thanks. I will take a look into that until the end of this week.

**Comment by djindjic** [comment]
hey sorry for delaying but my karma start command still works fine and exes just one hello world test:

``` bash
$ karma start
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 42.0.2311 (Linux)]: Connected on socket MgCc4Wxtjx-MXc4MFrrl with id 14057439

Start:
  Hello
    ✔ returns world

Finished in 0.011 secs / 0.001 secs

SUMMARY:
✔ 1 tests completed
```

do you have last version of generator?

**Comment by ghost** [comment]
This issue was opened because @BobbieBarker didn't have the `karma` binary available in path. Up [until April 24th](https://github.com/karma-runner/karma/commit/6823926f0588f4a219705eb648fbb36a933a32d5) it was required for users of Karma to `npm install -g karma-cli` to use karma from the command line. However, someone [snuck in a fix](https://github.com/karma-runner/karma/commit/6823926f0588f4a219705eb648fbb36a933a32d5) to https://github.com/karma-runner/karma/pull/1384 and you can now run Karma without the global dependency by running `./node_modules/karma/bin/karma start` once node dependencies are installed.

To ease the semantics of running tests you can pop the above command into `package.json` as the test script and simply call `npm test` from the command line. Here's what you need to add to the `scripts` node in your `package.json` to make that happen:

``` json
"scripts": {
  "test": "./node_modules/karma/bin/karma start"
},
```

**Note:** You may need to [set the path of your Chrome binary](https://github.com/karma-runner/karma/blob/master/docs/config/03-browsers.md#correct-path-to-browser-binary) for the test runner to kick off properly unless you're using [`karma-detect-browsers`](https://github.com/litixsoft/karma-detect-browsers).
